;--------------------------------------------------------
    ;TABLA DEL MENSAJE 2 "JHONATAN_REINALDO_GOMEZ_PESCA"
;----------------------------------------------------------
MENSAJE_2:
    ADDWF  PCL,F
    DT	   0X3C, 0X37, 0X7E, 0X15, 0X77, 0X70, 0X77, 0X15, 0X08, 0X05
    DT     0X4F, 0X30, 0X15, 0X77, 0X0E, 0X3D, 0X7E, 0X08, 0X5F, 0X7E
    DT     0X15, 0X15, 0X4F, 0X6D, 0X08, 0X67, 0X4F, 0X5B, 0X4E, 0X77
    DT     0X00, 0X00, 0X00, 0X00

