;--------------------------------------------------------
    ;TABLA DEL MENSAJE 4 "CURSO_MICROCONTROLADORES_49-0"
;----------------------------------------------------------
MENSAJE_4:
    ADDWF  PCL,F
    DT	   0X4E, 0X3E, 0X05, 0X5B, 0X7E, 0X08, 0X15, 0X15, 0X30, 0X4E
    DT     0X05, 0X7E, 0X4E, 0X7E, 0X15, 0X70, 0X05, 0X7E, 0X0E, 0X77
    DT     0X3D, 0X7E, 0X05, 0X4F, 0X5B, 0X08, 0X33, 0X7B, 0X01, 0X7E
    DT     0X00, 0X00, 0X00

