;--------------------------------------------------------
    ;TABLA DEL MENSAJE 1 "FABIAN_STEVEN_ZEA_GONZALEZ_123"
;----------------------------------------------------------
MENSAJE_1:
    ADDWF  PCL,F
    DT	   0X47, 0X77, 0X1F, 0X30, 0X77, 0X15, 0X08, 0X5B, 0X70, 0X4F
    DT     0X3E, 0X4F, 0X15, 0X08, 0X6D, 0X4F, 0X77, 0X08, 0X5F, 0X7E
    DT     0X15, 0X6D, 0X77, 0X0E, 0X4F, 0X6D, 0X08, 0X30, 0X6D, 0X79
    DT     0X00, 0X00, 0X00, 0X00
