;--------------------------------------------------------
    ;TABLA DEL MENSAJE 3 "ESCUELA_INGENIERIA_ELECTRONICA"
;----------------------------------------------------------
MENSAJE_3:
    ADDWF  PCL,F
    DT	   0X4F, 0X5B, 0X4E, 0X3E, 0X4F, 0X0E, 0X77, 0X08, 0X30, 0X15
    DT     0X5F, 0X4F, 0X15, 0X30, 0X4F, 0X05, 0X30, 0X77, 0X08, 0X4F
    DT     0X0E, 0X4F, 0X4E, 0X70, 0X05, 0X7E, 0X15, 0X30, 0X4E, 0X77
    DT     0X00, 0X00, 0X00, 0X00





