;----------------------------------------------------
    ;UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA
    ;ESCUELA DE INGENIERIA ELECTRONICA
    ;MICROCONTROLADORES PRIMER SEMESTRE 2017
    ;LABORATORIO #2 TEMPRIZADOR Y VISION ESTREBOSCOPICA
    ;FABIAN STEVEN ZEA GONZALEZ
    ;201210733
    ;JHONATAN REINALDO GOMEZ PESCA
    ;201210146
lIST p=16f887
#include "p16f887.inc"


; CONFIG1
; __config 0xEFF2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF 
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

CBLOCK 0X20
 VENTANASEG
 VENTANAMIN
 VENTANAHOR

    
ENDC
CBLOCK 0X27
    ENTRADASEG
    ENTRADAMIN
    ENTRADAHOR
    SALIDAASEG
    SALIDABSEG
    SALIDAAMIN
    SALIDABMIN
    SALIDAAHOR
    SALIDABHOR
    CONTEO
    CONTEO2
    REGOP
    CONTA1
    CONTA2
    REG1
    REG2
    REG3
    REG4
    REG5
    REG6
    
ENDC   
ORG 0X00
;--------------------------------------
    ;PROGRAMA PRINCIPAL
;--------------------------------------
INICIO:
    CALL CONFIGURACION 
    CALL INIG_REG
START:
    BTFSS PORTE,RE1
    GOTO START

    
    CALL CONTADORDEC
    CALL CONTADORINC
    CALL PUBLIC
    CALL ESPERA
    
    GOTO START
    
    #INCLUDE "TABLA.INC"
    #INCLUDE"MENSAJE_1.INC"
    #INCLUDE"MENSAJE_2.INC"
    #INCLUDE"MENSAJE_3.INC"
    #INCLUDE"MENSAJE_4.INC"
    #INCLUDE"MENSAJE_5.INC"
    #INCLUDE "TABLAESPERA.INC"
    #INCLUDE "CONFIGURACION.INC"
    #INCLUDE "CONTADORDEC.INC"
    #INCLUDE "CONTADORINC.INC"
    #INCLUDE "CONVERSOR1.INC"
    #INCLUDE "CONVERSOR2.INC"
    #INCLUDE "CONVERSOR3.INC"
    #INCLUDE "INIG_REG.INC"
    #INCLUDE "RETARDO1.INC"
    #INCLUDE "T_ESCOGER.INC"
    #INCLUDE "ROTAR.INC"
    #INCLUDE"SALIDA_VISUAL.INC"
    
    #INCLUDE"ROTAR_CARACTER.INC"
    #INCLUDE"PUBLIC.INC"
    #INCLUDE "ESPERA.INC"
    
    END


